name: ecommerce
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  time_machine: ^0.9.17
  dio: ^5.4.0
  equatable: ^2.0.5
  google_fonts: 4.0.3
  cached_network_image: ^3.3.1
  flutter_bloc: ^8.1.3
  flutter_easyloading: ^3.0.5
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.5
  flutter_svg: ^2.0.9
  page_transition: ^2.1.0
  shared_preferences: ^2.2.2
  get_it: ^8.0.3
  internet_connection_checker: ^1.0.0+1
  font_awesome_flutter: ^10.7.0
  table_calendar: ^3.0.9
  flutter_rating_bar: ^4.0.1
  dartz: ^0.10.1
  pretty_dio_logger: ^1.4.0
  toastification: ^2.0.0
  lottie: ^3.0.0
  http: ^0.13.0
  google_nav_bar: ^5.0.6
  firebase_core: ^3.13.0
  firebase_messaging: ^15.0.2
  dots_indicator: ^3.0.0
  carousel_slider: ^5.0.0
  slide_to_act: ^2.0.2
  dotted_line: ^3.2.2
  intl_phone_number_input: ^0.7.4
  loading_animation_widget: ^1.2.1
  country_code_picker: ^3.0.0
  google_maps_flutter: ^2.9.0
  skeletonizer: ^1.4.2
  google_sign_in: ^6.3.0
  pin_code_fields: ^8.0.1
  easy_image_viewer: ^1.5.1
  geocoding: ^3.0.0
  smooth_corner_updated: ^1.0.0
  flutter_secure_storage: ^9.2.4
  socket_io_client: ^3.0.2
  responsive_framework: ^1.5.1
  webview_flutter: ^4.10.0
  ntp: ^2.0.0
  rename: ^3.0.2
  url_launcher: ^6.3.1
  app_tracking_transparency: ^2.0.6+1
  sign_in_with_apple: ^7.0.1
  package_info_plus: ^8.3.0
  image_picker: ^1.1.2
  dotted_border: ^2.1.0
  simple_star_rating: ^0.0.3
  permission_handler: ^12.0.0+1
  shimmer: ^3.0.0
  camera: ^0.11.1
  share_plus: ^11.0.0
  geolocator: ^11.0.0
  maps_launcher: ^3.0.0+1
  fluttertoast: ^8.2.12
  awesome_snackbar_content: ^0.1.5
  json_annotation: ^4.9.0
  niddler_dart: ^1.6.0
  jwt_decoder: ^2.0.1
  image: ^4.3.0
  pinch_zoom: ^2.0.1
  talker: ^4.7.9
  infinite_scroll_pagination: ^4.1.0
  pull_to_refresh: ^2.0.0
  timeago: ^3.7.1
  flutter_screenutil: ^5.9.3
  injectable: ^2.5.1
  readmore: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.6.0
  injectable_generator: ^2.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

# 👇 Keep this OUTSIDE the flutter: section
flutter_native_splash:
  color: "#004182"
  image: assets/images/app_splash.png
  android: true
  ios: true
  web: false
  android_12:
    color: "#004182"
    image: assets/images/app_splash.png
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#004182"
